### ISSUE TITLE
IMAGE_FORMAT env var not set when testing against stable OCP release

### ISSUE THREAD

**Issue by mgencur** [openshift/ci-tools#1187]
When using the following configuration instead of `tag_specification`, the IMAGE_FORMAT variable is empty in the test environment:
```
releases:
  latest:
    release:
      channel: stable
      version: "4.5"
```

This is a problem because the images that are built by ci-operator for the current run are not easily accessible.

Link to the test run that has the empty env variable: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/11443/rehearse-11443-pull-ci-openshift-knative-serverless-operator-master-4.5-upstream-e2e-aws-ocp-45/1300444362731163648/build-log.txt
