### ISSUE TITLE
ci-operator: additional images for publishing are not built if they are not used

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/ci-tools#284]
See [this configuration](https://github.com/openshift/release/blob/a96eb16981761d553b89b7ed76688e72515372a6/ci-operator/config/openshift/origin/openshift-origin-master.yaml#L188-L191) from Origin:

```
tests:
- as: images-artifacts
  commands: '# noop, just to force the building the `artifacts` image'
  container:
    from: artifacts
```

We should build this in the `[images]` target, if we don't.

@tnozicka
